version: '3.4'

services:


  rabbitmq:
    hostname: rabbit
    ports:
      - "5672:5672"

  messaging.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/messaging

    ports:
      - "6011:80"
      #- "6012:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  mapping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbit
      - PATH_BASE=/mapping

    ports:
      - "6013:80"
      #- "6014:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  formulary.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=rabbit
      - PATH_BASE=/formulary

    ports:
      - "6015:80"
      #- "6016:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  acceptance.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/acceptance
    ports:
      - "6017:80"
      #- "6018:443"
    #hostname: acceptance
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=messaging HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://messaging.api/hc
      - HealthChecksUI__HealthChecks__1__Name=mapping HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://mapping.api/hc
      - HealthChecksUI__HealthChecks__2__Name=formulary.api HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://formulary.api/hc
      - HealthChecksUI__HealthChecks__3__Name=acceptance HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://acceptance.api/hc
    ports:
      - "6020:80"


 
